MavAutoKozm/Models/User.cs
namespace MavAutoKozm.Models
{
    public class User
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstMidName { get; set; }

        public string Email { get; set; }

        public string PhoneNumber { get; set; }

        //FK: regisztrált user-hez való kötés
        //9eac65ed-c99b-4087-8496-7b4fef719677
        public string AspNetUserId { get; set; }

        //navigációs property
        public ICollection<Vehicle> Vehicles { get; set; }

        //tovább fejlesztési lehetőségek (pl: vevő értékelés)
    }
}

MavAutoKozm/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MavAutoKozm.Data;
using MavAutoKozm.Models;
using static System.Net.WebRequestMethods;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace MavAutoKozm.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private readonly string _felhasznaloId = "FelhasznaloId";
        //private readonly MavAutoKozmDbContext _context;
        private readonly IMavAutoKozmRepository _context; //Ezzel éri el az adatbázist

        private UserManager<IdentityUser> _userManager;

        public UsersController(IMavAutoKozmRepository context, UserManager<IdentityUser> userMgr)
        {
            _context = context;
            _userManager = userMgr;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            if (User != null)
            {
                //Dolgozó vagy Adminnak teljes lista jelenik meg
                if (User.IsInRole("Admin") || User.IsInRole("Alkalmazott"))
                    return _context.AppUsers != null ?
                              View(_context.AppUsers.ToList()) :
                              Problem("Entity set 'MavAutoKozmDbContext.Users'  is null.");
            }
            //Ha nincs felhasználója akkor létrehozunk egyet
            //Ha van akkor meg a Details-be küldjük
            var FelhasznaloId = HttpContext?.Session.GetInt32(_felhasznaloId);
            if (FelhasznaloId==null)
            {
                return RedirectToAction("Create");
            }
            else
            {
                return RedirectToAction("Details", new { id = FelhasznaloId });
            }
        }

        /// <summary>
        /// Felhasználók részletei
        /// </summary>
        /// <param name="id">userId</param>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AppUsers == null)
            {
                return NotFound();
            }

            //var user = await _context.AppUsers.Include(v => v.Vehicles)
            //   .FirstOrDefaultAsync(m => m.ID == id);  "Az Include-al egyszerűen hozzáadtuk a User.hez a jármű táblát"
              
            var user = _context.AppUsers.FirstOrDefault(m => m.ID == id);
            
            if (user == null)
            {
                return NotFound();
            }

            user.Vehicles =_context.Vehicles.FindAll(v => v.AppUserId == id);

            return View(user);
        }

        /// <summary>
        /// Felhasználók létrehozása
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {                      
            return View();
        }

        /// <summary>
        /// Felhasználók létrehozása
        /// </summary>
        /// <param name="user">userId</param>
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,LastName,FirstMidName,Email,PhoneNumber,AspNetUserId")] AppUser user)
        {
            //if (ModelState.IsValid)           
            {
                user.AspNetUserId = User.Claims.FirstOrDefault
                (x => x.Type == "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier")?.Value;
                
                _context.AppUsersAdd(user);
                
                HttpContext.Session.SetInt32(_felhasznaloId, user.ID);

                return RedirectToAction("Details", new { id = user.ID });
            }
            return View(user);
        }

        /// <summary>
        /// Felhasználók szerkesztése
        /// </summary>
        /// <param name="id">userId</param>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AppUsers == null)
            {
                return NotFound();
            }

            var user = _context.AppUsers.Find(x => x.ID == id);//Include(v => v.Vehicles)
            if (user == null)
            {
                return NotFound();
            }
            user.Vehicles = new List<Vehicle>();
            return View(user);
        }

        /// <summary>
        /// Felhasználók szerkesztése
        /// </summary>
        /// <param name="id"></param>
        /// <param name="user"></param>
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,LastName,FirstMidName,Email,PhoneNumber,AspNetUserId")] AppUser user)
        {
            if (id != user.ID)
            {
                return NotFound();
            }

            //if (ModelState.IsValid)
            {
                try
                {
                    _context.AppUsersUpdate(user);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        /// <summary>
        /// Felhasználók törlése
        /// </summary>
        /// <param name="id">userId</param>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.AppUsers == null)
            {
                return NotFound();
            }

            var user = _context.AppUsers
                .FirstOrDefault(m => m.ID == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        /// <summary>
        /// Felhasználók törlése
        /// </summary>
        /// <param name="id">userId</param>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.AppUsers == null)
            {
                return Problem("Entity set 'MavAutoKozmDbContext.AppUsers'  is null.");
            }
            var user = _context.AppUsers.Find(x => x.ID == id);
            if (user != null)
            {
                _context.AppUsersDelete(user);
            }
            
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> ChangeRole(int? appuserid) 
        {
            var appuser = _context.AppUsers.Find(x => x.ID == appuserid);
            var result = await _userManager.AddToRoleAsync(_userManager.FindByIdAsync(appuser.AspNetUserId).Result, "Alkalmazott");
            return RedirectToAction("Roles","Role");
        }

        public bool UserExists(int id)
        {
          return (_context.AppUsers?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

MavAutoKozm/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MavAutoKozm.Data;
using MavAutoKozm.Models;
using Microsoft.AspNetCore.Authorization;

namespace MavAutoKozm.Controllers
{
    [Authorize]
    public class VehiclesController : Controller
    {
        private readonly string _felhasznaloId= "FelhasznaloId";
        //private readonly MavAutoKozmDbContext _context;
        private readonly IMavAutoKozmRepository _context; //Ezzel éri el az adatbázist


        public VehiclesController(IMavAutoKozmRepository context)
        {
            _context = context;
        }

        // GET: Vehicles
        public async Task<IActionResult> Index()
        {
            if (User.IsInRole("Admin") || User.IsInRole("Alkalmazott"))
                return _context.Vehicles != null ?
                          View(_context.Vehicles.ToList()) :
                          Problem("Entity set 'MavAutoKozmDbContext.Vehicles'  is null.");


            var FelhasznaloId = HttpContext.Session.GetInt32(_felhasznaloId);

            return _context.Vehicles != null ?
                          View(_context.Vehicles.Where(jarmu => jarmu.AppUserId == FelhasznaloId).ToList()) :
                          Problem("Entity set 'MavAutoKozmDbContext.Vehicles'  is null.");
        }

        /// <summary>
        /// Járművek részleteit mutatja
        /// </summary>
        /// <param name="id">autoId</param>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle =_context.Vehicles
                .FirstOrDefault(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        /// <summary>
        /// Járművek létrehozása
        /// </summary>
        /// <returns></returns>
        public IActionResult Create()
        {
            var vehicle = new Vehicle();
            if (HttpContext != null)
                vehicle.AppUserId = HttpContext.Session.GetInt32(_felhasznaloId).Value; //Figyelem ez Null is lehet
            
            return View(vehicle);
        }

        /// <summary>
        /// Járművek létrehozása
        /// </summary>
        /// <returns></returns>
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,AppUserId,Brand,Model,Type,Color,NumberPlate")] Vehicle vehicle)
        {
            if (ModelState.IsValid)
            {
               
                _context.VehiclesAdd(vehicle);
                return RedirectToAction(nameof(Index));
            }
            return View(vehicle);

        }

        /// <summary>
        /// Járművek szerkesztése
        /// </summary>
        /// <param name="id">autoId</param>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle = _context.Vehicles.Find(x => x.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }
            return View(vehicle);
        }

        /// <summary>
        /// Járművek szerkesztése
        /// </summary>
        /// <param name="id">autoId</param>
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AppUserId,Brand,Model,Type,Color,NumberPlate")] Vehicle vehicle)
        {
            if (id != vehicle.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.VehiclesUpdate(vehicle);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehicle);
        }

        /// <summary>
        /// Járművek törlése
        /// </summary>
        /// <param name="id">autoId</param>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vehicles == null)
            {
                return NotFound();
            }

            var vehicle = _context.Vehicles
                .FirstOrDefault(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        /// <summary>
        /// Járművek törlése
        /// </summary>
        /// <param name="id">autoId</param>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vehicles == null)
            {
                return Problem("Entity set 'MavAutoKozmDbContext.Vehicles'  is null.");
            }
            var vehicle = _context.Vehicles.Find(v => v.Id == id);
            if (vehicle != null)
            {
                _context.VehiclesDelete(vehicle);
            }
            
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(int id)
        {
          return (_context.Vehicles?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MavAutoKozm/Views/Users/Create.cshtml
@model MavAutoKozm.Models.AppUser
<link rel=" stylesheet " href="~/css/foOldal.css" asp-append-version="true" />
@{
    ViewData["Title"] = "Create";
}

<h1>Adatok megadása</h1>
<hr />
<div class="">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">@MavAutoKozm.Resources.Resource.Vezetéknév</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstMidName" class="control-label">@MavAutoKozm.Resources.Resource.Keresztnév</label>
                <input asp-for="FirstMidName" class="form-control" />
                <span asp-validation-for="FirstMidName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">@MavAutoKozm.Resources.Resource.Email</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label">@MavAutoKozm.Resources.Resource.Telefonszám</label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <!-- <label asp-for="AspNetUserId" class="control-label"></!--label> -->
                <input asp-for="AspNetUserId" class="form-control" />
                <span asp-validation-for="AspNetUserId" class="text-danger"></span>
            </div>
            <p></p>
            <div class="form-group">
                <input type="submit" value="@MavAutoKozm.Resources.Resource.Mentés" style="padding: 15px;
                                margin: 50px 0px;
                                width: 220px;
                                font-size: 15px;
                                background: lightblue;
                                border-radius: 10px;
                                font-weight: 800;
                                box-shadow: 3px 3px 0px 0px black;
                                text-align:center" />
            </div>
        </form>
    </div>
</div>
<p></p>
<div>
    <a class="foOldalGombja nav-link text-dark" asp-action="Index">@MavAutoKozm.Resources.Resource.Vissza_a_listába</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MavAutoKozm/Views/Users/Delete.cshtml
@model MavAutoKozm.Models.AppUser

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AspNetUserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AspNetUserId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MavAutoKozm/Views/Users/Details.cshtml
@model MavAutoKozm.Models.AppUser
<link rel=" stylesheet " href="~/css/foOldal.css" asp-append-version="true" />
@{
    ViewData["Title"] = "Részletek";
}

<img src="~/css/image/3cf626720ae64fb5a5b5d9eab9e8c185.png" alt="LOGO" style="float:right;width:90px;height:90px;" />
<h1>@MavAutoKozm.Resources.Resource.Részletek</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @MavAutoKozm.Resources.Resource.Vezetéknév
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @MavAutoKozm.Resources.Resource.Keresztnév
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>
        <dt class = "col-sm-2">
            @MavAutoKozm.Resources.Resource.Email
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @MavAutoKozm.Resources.Resource.Telefonszám
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AspNetUserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AspNetUserId)
        </dd>

        <dt class="col-sm-2">
            @MavAutoKozm.Resources.Resource.Járműveim
        </dt>
        <dd class="col-sm-10">
            @if (Model.Vehicles is not null)
            {
                @foreach (var item in Model.Vehicles)
                {
                    <a asp-controller="Vehicles" asp-action="Details" asp-route-id="@item.Id">@item.NumberPlate</a>
                }  
            }
            
        </dd>
    </dl>
</div>
<div>
    <a style="margin-right:30px;" class="foOldalGombja nav-link text-dark" asp-action="Edit" asp-route-id="@Model?.ID">@MavAutoKozm.Resources.Resource.Szerkesztés</a>
</div>

MavAutoKozm/Views/Users/Edit.cshtml
@model MavAutoKozm.Models.AppUser
<link rel=" stylesheet " href="~/css/foOldal.css" asp-append-version="true" />
@{
    ViewData["Title"] = "Szerkesztés";
}

<img src="~/css/image/3cf626720ae64fb5a5b5d9eab9e8c185.png" alt="LOGO" style="float:right;width:90px;height:90px;" />
<h1>@MavAutoKozm.Resources.Resource.Szerkesztés</h1>


<hr />
<div>
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="LastName" class="control-label">@MavAutoKozm.Resources.Resource.Keresztnév</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstMidName" class="control-label">@MavAutoKozm.Resources.Resource.Vezetéknév</label>
                <input asp-for="FirstMidName" class="form-control" />
                <span asp-validation-for="FirstMidName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label">@MavAutoKozm.Resources.Resource.Email</label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label">@MavAutoKozm.Resources.Resource.Telefonszám </label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <!-- <label asp-for="AspNetUserId" class="control-label"></!--label> -->
                <input asp-for="AspNetUserId" class="form-control" />
                <span asp-validation-for="AspNetUserId" class="text-danger"></span>
            </div>

            <table aria-hidden="true">
                <tr>
                    <td>
                        <p></p>
                        @if (User.IsInRole("Admin"))
                        {
                            <div>
                                <a style="margin-right:30px;" class="foOldalGombja nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Index">@MavAutoKozm.Resources.Resource.Járművek</a>
                            </div>
                        }
                        else
                        {
                            <div>
                                <a style="margin-right:30px;" class="foOldalGombja nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Index">@MavAutoKozm.Resources.Resource.Járműveim</a>
                            </div>
                        }
                        
                    </td>
                    <td>
                            @if (User.IsInRole("Admin"))
                        {
                            <p></p>
                            <a class="foOldalGombja nav-link text-dark" style="width: 300px" asp-area="" asp-controller="Users" asp-action="ChangeRole" asp-route-appuserid="@Model.ID">@MavAutoKozm.Resources.Resource.Alkalmazottá_alakítás</a>
                        }
                    </td>
                    <td>
                        <div style="margin-right:30px;" class="foOldalGombja nav-link text-dark">
                            <input type="submit" class="" value="@MavAutoKozm.Resources.Resource.Mentés" style="padding: 15px;
                                margin: 15px 0px;
                                width: 220px;
                                font-size: 15px;
                                background: lightblue;
                                border-radius: 10px;
                                font-weight: 800;
                                box-shadow: 3px 3px 0px 0px black;
                                text-align:center" />
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div>
                            <a class="foOldalGombja nav-link text-dark" asp-action="Index">@MavAutoKozm.Resources.Resource.Vissza_a_listába</a>
                        </div>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MavAutoKozm/Views/Users/Index.cshtml
<link rel=" stylesheet " href="~/css/foOldal.css" asp-append-version="true" />
@model IEnumerable<MavAutoKozm.Models.AppUser>

@{
    ViewData["Title"] = "Felhasználók";
}

<h1>Index</h1>

@if(!Model.Any()){
    <h1>Ön még nem rendelkezik felhasználói adatokkal!</h1>
    <p>
        <a asp-action="Create">Létrehozás</a>
    </p>
}
else
{

    <table class="table" aria-hidden="true">
        <thead>
            <tr>
                <th>
                    @MavAutoKozm.Resources.Resource.Keresztnév
                </th>
                <th>
                    @MavAutoKozm.Resources.Resource.Vezetéknév
                </th>
                <th>
                    @MavAutoKozm.Resources.Resource.Email
                </th>
                <th>
                    @MavAutoKozm.Resources.Resource.Telefonszám
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AspNetUserId)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstMidName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AspNetUserId)
                </td>
                <td>
                        <a asp-action="Edit" asp-route-id="@item.ID">@MavAutoKozm.Resources.Resource.Szerkesztés</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">@MavAutoKozm.Resources.Resource.Részletek</a> |
                        <a style="color:red" asp-action="Delete" asp-route-id="@item.ID">@MavAutoKozm.Resources.Resource.Törlés</a>
                </td>
            </tr>
    }
        </tbody>
    </table>

}